# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 263)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(3, 70, 71, 32))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 70, 71, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(138, 70, 71, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(3, 100, 71, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 100, 71, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(138, 100, 71, 32))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(3, 130, 71, 32))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(70, 130, 71, 32))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(138, 130, 71, 32))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(70, 160, 71, 32))
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_o = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_o.setGeometry(QtCore.QRect(3, 160, 71, 32))
        self.pushButton_o.setObjectName("pushButton_.")
        self.pushButton_AC = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AC.setGeometry(QtCore.QRect(138, 160, 71, 32))
        self.pushButton_AC.setObjectName("pushButton_AC")
        self.pushButton_jia = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_jia.setGeometry(QtCore.QRect(210, 70, 71, 32))
        self.pushButton_jia.setObjectName("pushButton_+")
        self.pushButton_jian = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_jian.setGeometry(QtCore.QRect(210, 100, 71, 32))
        self.pushButton_jian.setObjectName("pushButton_-")
        self.pushButton_cheng = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cheng.setGeometry(QtCore.QRect(210, 130, 71, 32))
        self.pushButton_cheng.setObjectName("pushButton_*")
        self.pushButton_chu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_chu.setGeometry(QtCore.QRect(210, 160, 71, 32))
        self.pushButton_chu.setObjectName("pushButton_/")
        self.pushButton_del = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_del.setGeometry(QtCore.QRect(3, 190, 71, 32))
        self.pushButton_del.setObjectName("pushButton_del")
        self.pushButton_w = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_w.setGeometry(QtCore.QRect(70, 190, 71, 32))
        self.pushButton_w.setObjectName("pushButton_=")
        self.pushButton_x = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_x.setGeometry(QtCore.QRect(138, 190, 71, 32))
        self.pushButton_x.setObjectName("pushButton_<")
        self.pushButton_d = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_d.setGeometry(QtCore.QRect(210, 190, 71, 32))
        self.pushButton_d.setObjectName("pushButton_>")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(11, 10, 261, 61))
        self.lcdNumber.setObjectName("lcdNumber")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 282, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_1.clicked.connect(MainWindow.btn1)
        self.pushButton_2.clicked.connect(MainWindow.btn1)
        self.pushButton_5.clicked.connect(MainWindow.btn1)
        self.pushButton_7.clicked.connect(MainWindow.btn1)
        self.pushButton_4.clicked.connect(MainWindow.btn1)
        self.pushButton_8.clicked.connect(MainWindow.btn1)
        self.pushButton_o.clicked.connect(MainWindow.btn1)
        self.pushButton_0.clicked.connect(MainWindow.btn1)
        self.pushButton_3.clicked.connect(MainWindow.btn1)
        self.pushButton_jia.clicked.connect(MainWindow.btn1)
        self.pushButton_6.clicked.connect(MainWindow.btn1)
        self.pushButton_jian.clicked.connect(MainWindow.btn1)
        self.pushButton_9.clicked.connect(MainWindow.btn1)
        self.pushButton_cheng.clicked.connect(MainWindow.btn1)
        self.pushButton_chu.clicked.connect(MainWindow.btn1)
        self.pushButton_w.clicked.connect(MainWindow.btn1)
        self.pushButton_x.clicked.connect(MainWindow.btn1)
        self.pushButton_d.clicked.connect(MainWindow.btn1)
        self.pushButton_AC.clicked.connect(MainWindow.btn1)
        self.pushButton_del.clicked.connect(MainWindow.btn1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Computer"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_o.setText(_translate("MainWindow", "."))
        self.pushButton_AC.setText(_translate("MainWindow", "AC"))
        self.pushButton_jia.setText(_translate("MainWindow", "+"))
        self.pushButton_jian.setText(_translate("MainWindow", "-"))
        self.pushButton_cheng.setText(_translate("MainWindow", "*"))
        self.pushButton_chu.setText(_translate("MainWindow", "/"))
        self.pushButton_del.setText(_translate("MainWindow", "删除"))
        self.pushButton_w.setText(_translate("MainWindow", "="))
        self.pushButton_x.setText(_translate("MainWindow", "<"))
        self.pushButton_d.setText(_translate("MainWindow", ">"))


